=== alexandrasophiapetersen/Cplusplus1/Zielformat.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT sendungsliste (sender+)>
<!ELEMENT sender (sendername,sendung+)>
<!ELEMENT sendername (#PCDATA)>
<!ELEMENT sendung (meta+,episoden+)>
<!ATTLIST sendung id ID #REQUIRED >
<!ELEMENT meta (sendungsname, genre, ausstrahlungszeit, ausstrahlungsdauer)>
<!ELEMENT sendungsname (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT ausstrahlungszeit (#PCDATA)>
<!ELEMENT ausstrahlungsdauer (#PCDATA)>
<!ELEMENT episoden (staffel)>
<!ELEMENT staffel (#PCDATA)>

<!ATTLIST staffel nummer CDATA #REQUIRED>

=== alexandrasophiapetersen/Cplusplus1/Zielformat.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sendungsliste SYSTEM "Zielformat.dtd">
<sendungsliste>
    <sender>
        <sendername>VOX</sendername>
        <sendung id="A1"><episoden>
            <staffel nummer="S1">20</staffel>
        </episoden>
            <episoden>
                <staffel nummer="S2">47</staffel>
            </episoden>
            <episoden>
                <staffel nummer="S3">33</staffel>
            </episoden>
            <sendungsname>Mein Kind, dein Kind - Wie erziehst du denn?</sendungsname>
            <genre>Tägliche Serie</genre>
            <ausstrahlungszeit>täglich</ausstrahlungszeit>
            <ausstrahlungsdauer>5 Jahre</ausstrahlungsdauer>
        </sendung>
        <sendung id="A2"><episoden>
            <staffel nummer="S1">12</staffel>
        </episoden>
            <episoden>
                <staffel nummer="S2">12</staffel>
            </episoden>
            <episoden>
                <staffel nummer="S3">12</staffel>
            </episoden>
            <episoden>
                <staffel nummer="S4">12</staffel>
            </episoden>
            <sendungsname>Shopping Queen</sendungsname>
            <genre>Tägliche Serie</genre>
            <ausstrahlungszeit>täglich</ausstrahlungszeit>
            <ausstrahlungsdauer>15 Jahre</ausstrahlungsdauer>
        </sendung>
        <sendung id="A3"><episoden>
            <staffel nummer="S1">11</staffel>
        </episoden>
            <episoden>
                <staffel nummer="S2">16</staffel>
            </episoden>
            <sendungsname>auto mobil</sendungsname>
            <genre>Auto</genre>
            <ausstrahlungszeit>Sonntag</ausstrahlungszeit>
            <ausstrahlungsdauer>3 Jahre</ausstrahlungsdauer>
        </sendung>
    </sender>
    <sender>
        <sendername>RTL</sendername>
        <sendung id="B1"><episoden>
            <staffel nummer="S1">10</staffel>
        </episoden>
            <episoden>
                <staffel nummer="S2">11</staffel>
            </episoden>
            <episoden>
                <staffel nummer="S3">9</staffel>
            </episoden>
            <sendungsname>Wer wird Millionär?</sendungsname>
            <genre>Show</genre>
            <ausstrahlungszeit>Montag Primetime</ausstrahlungszeit>
            <ausstrahlungsdauer>25 Jahre</ausstrahlungsdauer>
        </sendung>
        <sendung id="B2"><episoden>
            <staffel nummer="S1">8</staffel>
        </episoden>
            <episoden>
                <staffel nummer="S2">13</staffel>
            </episoden>
            <episoden>
                <staffel nummer="S3">16</staffel>
            </episoden>
            <episoden>
                <staffel nummer="S4">12</staffel>
            </episoden>
            <sendungsname>Bauer sucht Frau</sendungsname>
            <genre>Show</genre>
            <ausstrahlungszeit>Dienstag Primetime</ausstrahlungszeit>
            <ausstrahlungsdauer>15 Jahre</ausstrahlungsdauer>
        </sendung>
        <sendung id="B3"><episoden>
            <staffel nummer="S1">12</staffel>
        </episoden>
            <episoden>
                <staffel nummer="S2">10</staffel>
            </episoden>
            <episoden>
                <staffel nummer="S3">21</staffel>
            </episoden>
            <episoden>
                <staffel nummer="S4">12</staffel>
            </episoden>
            <episoden>
                <staffel nummer="S5">13</staffel>
            </episoden>
            <episoden>
                <staffel nummer="S6">11</staffel>
            </episoden>
            <sendungsname>Deutschland sucht den Superstar</sendungsname>
            <genre>Show</genre>
            <ausstrahlungszeit>Samstag Primetime</ausstrahlungszeit>
            <ausstrahlungsdauer>20 Jahre</ausstrahlungsdauer>
        </sendung>
    </sender>
    <sender>
        <sendername>RTL2</sendername>
        <sendung id="C1"><episoden>
            <staffel nummer="S1">17</staffel>
        </episoden>
            <episoden>
                <staffel nummer="S2">15</staffel>
            </episoden>
            <sendungsname>Berlin - Tag und Nacht</sendungsname>
            <genre>Tägliche Serie</genre>
            <ausstrahlungszeit>täglich</ausstrahlungszeit>
            <ausstrahlungsdauer>2 Jahre</ausstrahlungsdauer>
        </sendung>
        <sendung id="C2"><episoden>
            <staffel nummer="S1">16</staffel>
        </episoden>
            <episoden>
                <staffel nummer="S2">13</staffel>
            </episoden>
            <episoden>
                <staffel nummer="S3">14</staffel>
            </episoden>
            <sendungsname>BABYs! Kleines Wunder - großes Glück</sendungsname>
            <genre>Familie</genre>
            <ausstrahlungszeit>Montag Primetime</ausstrahlungszeit>
            <ausstrahlungsdauer>10 Jahre</ausstrahlungsdauer>
        </sendung>
        <sendung id="C3"><episoden>
            <staffel nummer="S1">11</staffel>
        </episoden>
            <episoden>
                <staffel nummer="S2">12</staffel>
            </episoden>
            <episoden>
                <staffel nummer="S3">11</staffel>
            </episoden>
            <sendungsname>Die Geissens</sendungsname>
            <genre>Show</genre>
            <ausstrahlungszeit>Dienstag Primetime</ausstrahlungszeit>
            <ausstrahlungsdauer>5 Jahre</ausstrahlungsdauer>
        </sendung>
    </sender>
</sendungsliste>
